---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pg-credentials
  namespace: code-place-dev
spec:
  encryptedData:
    password: AgABlnZk8w3hIX/Xj2UmvYtjltwCTFh1vckMSGiCHimTEo4B8767MendhzjB7VLg1nUgGsI3FeToBKN9X3ZkFJ2thpyso2pQ0CwlnuWA8LGLrfWHztbAUP2ejMKBiJdAGwDNhjoJXDA3tijdnsCGCxPvdA+NHE8f1Og00zsimmjRaJW87zPoiPD+AHZlCvW/wKwTYJUNa2R0KIcEwTiHx3iayizumIIX25lx2DSMq/cRw75B90rGZ/Ji9B9q8zgY0hJ5M/mQmxsmuEYylD/nKhh20gqiD/UxM60rThWYHPk4LQToazxr0uSxLW2HXJfjrV4+ux+w1X6j5JNymbmeG1Rov5TwILmwk7iWh1iFGOWt1CyM0QwELojRs2VLCL77gbJfaxj5LA4Y6V1MxHq8+RNhpE4V2GozKMFH3t/Uw5TmYRdl1p8CEM/GIlb8TEmfjo2tfTHMA4ALnKhDtQt+RAOlhvJgj/aKXPaSbOE51YBQLWC2TCRsjrZLkrQEWOulY6zg6EwIKLq6JEQmsntOiRKg49kB6xd8iaS5QAbEmpYxNRKo5oU1/wWf7TgIo1B7jK9vQpBD/ygMmanTTjE5Uim2KwvKBqXp6FmnR51m4mrH3OMPZGr282pIQkjcZvPFySyBovGzcKMLx9ILqjYwaUrgSutzPO+VLbua4d8ilj3J1N6/O9xbZBee2tmqzbxa3zBDkAP0
    username: AgCCvmUxoj7d7IQsX8a4oAp+Y/bHmO6qzKW6NAz+Z/x7E/FsP4v59WKbgj+fto8Ex2WeRhQ81gsOQhoS3Xh6ZNsCliI3gNsF9h7KACwtVXz5W4n7/qJH2sRNXG0tU9bWFYtt4sg/j42/eIAMvG8mkJRh2UfS/AyAD2HE7HbNpt+a/oBwZuU5IglgPERAMYRqZwwL5BsILellJmMEs/87YhJGdgK/CHDzvI1aX4l192jxoyUc1+QlDiFRgEdVFnNVZGa/+Op4I7m1AOgOa6pthysj7adWnN0bllV5JRsT7MdidDThpUmeUtRph1IojBhOGg2CLeT534jYdeBlfch+6FJcLWxdMKkA/3KKWsx+Gq1pBKIZgsXeaxM/4AZ9NspAB+0xgkIYGeo0KDfKpzDpa/6iKumF42SGJ63Ewuns3NZeZEvpsMW1pB/htliMP571PWccVIe9Q1IY3Zvldug69HZtPieXTXv3jy/Irvg4zoAAnayCYA6b+ENJzfTWsd0haVwW+DyH93xR86zX5Y9LyyzI8yhm6Xg4Fu4bcjMhgIGIj670Ff626tY6km2RGCcIffuJFfkDMz31TNQJyFms2gUD8hB1km2516fqSeK/Ni3LBXtCrlWzIiRmVD3VmwTaLTRq7V3+HKXQLRnUGBcY80Nb1s1enHqe0ekfHnNppA8wxaua0p9D0fuF9x8nkRqGW70dELzf
  template:
    metadata:
      name: pg-credentials
      namespace: code-place-dev
