apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: regcred
  namespace: code-place-dev
spec:
  encryptedData:
    .dockerconfigjson: AgDA1YHbhlUP+4YVxYnKA6pp+rwBPVD6OlU3gCfRSfBdaKu4LhoBe4bL2iNS8Do9tZah/+Gv7EVi6petE0ncSbFSrtLrLkUShlULGJq9wg9ZBmL0MwfCO4Ctfzgv6AQN/MMbNsCI22Iuc3t4ohWzpjO2z45w76SK2b38lRwc/v+FSEFaCqHmN2a7sqWkYca+HJ9qFAJ4BQSSPmtpgbR5c9Gnc/xTmN/4HnCO2RPBYWxA3wANB028wI6Oz3B/Fe09AlKgXQqz3/REPTpjsC+TNPwF+1Z4rGf7sN9/m+IRgled7j6oD9gsQ6XgUTdKjYJ8MFcd/qoOT51n9Fcw0aaxr08O9ohtiQBgXvfX4tuqY9i6aWshsy0i29wqAsWmSswg8Oe0EsG/ns3FuNao/eHSO+FmqqIem4D7qjcn6OjpeAAcvPkFme+MzXyBPHTSsaM344KfciCmw0HIk/n693T/Ow+cUF7CHEF9bkcChhmaYKXtpenucTQWfz1ncFky0TPZWJjqvvU8LXfXfKlwwwVi8Ikph+ecTan5SpyWP8t2PpRwAsGoSOw4n9h1yXfFyWJrSEbZU6yVu2nyxsMXhUaMSN8fdvUzgtFRPfPO0RIewVagnZxDzSPNLkSRKpS2j90nGnmumLwe6VKna/iKJcbkJoKopcsXn4ApqgRiqZcaSPoZnBF6iqrwThYFoAK9U/1xkLuJwvWVGsdpkMsY9sZDMi72hq04huSR6Q5Lj6s86N3KEIDv84oVHPiUPTJFjLcPe5eo10uHYZ/47MgPgjR1w2k6+S+33HmMrr1TGi9URL0y5clh04Lul3W2sCorgSKQTZluTKihDJa/GPDcJmxSeVO/3YmiT10ad2NA
  template:
    metadata:
      name: regcred
      namespace: code-place-dev
    type: kubernetes.io/dockerconfigjson
