apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: regcred
  namespace: code-place-dev
spec:
  encryptedData:
    .dockerconfigjson: AgA2KGUgWQOTZM+Arl+ICvewtD7c3UTiMJvjXO5aB+HpHpOrVDIPxr0rwkPBv2fwNnaQEymOKQRL8pf+XM5WHIJnAWziCcrIVe99DIuII21MMigby8VF/tpIiB/rpcfq4pv9wXQNLnyd5JHul+xOk96uQV95kl6X/YCfvIGT5hwpAV0TvpsJvzR3OEUeAhh/ckhw6RGNg4k9XquSGUfIvxAPAoNCMceYSp+H8mMJTojqJY1+Hhx+JBpH76IVsZktHW+Pd1ssTJmFIzOA3r/kDoss/xYU7wMxHrHLnY2xVaZCNzVcB8rF3yUqsPxIEbvhOuCCuGVEQrF44y050KI+M5Yzo5p4r5E/CnzZtgOqnwl/U4bnIWmvML/dcDFHDD7SUtJzNE17aS1Jfuo0A6x6+FZK/71pUi50uuzI3bSiXNnF0k4IWQm7CR+1hpNTTjWj0L9YSJKVU2M9m3ue0aqxYAP5xEB1okFqpP9UdFo3IG8Rc59yVClfy1IeNawW/F+jq6gdIsBXpHSj2X3GjBE3TlZEAuRRXyWJiN/cBo6K6z+7UQBUYB160+zite4tVMo5u0Udta0wH2E9kTWw8M5aeFy7yLhLiCJxR8P8FSYJ7TTGq0EOiqbZlgUfqtRkFIJpeuC65WmkvGqH53/p7iWHVt+dw4+rogf+spKfqRc7hmriKVbVit9IQKnmNMAjuSZiSXK/ZLaYq7aUCM4u9ulTuAcy1bHl4xXefiajpNG3JUCEiq8FppJGzh+Uy6KSEecC5tewUs+Hmi3DSWqZPlziWxZKm7MAPOKXs43k8f4btr5Nw15+kwfEjCSpS2TquxnLQk8vLtSFSrP1aET7KahtpN72YpvJPRBi4w==
  template:
    metadata:
      name: regcred
      namespace: code-place-dev
    type: kubernetes.io/dockerconfigjson
