apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres
spec:
  instances: 3

  imageName: ghcr.io/cloudnative-pg/postgresql:14.12

  primaryUpdateStrategy: unsupervised

  storage:
    storageClass: longhorn
    size: 30Gi

  bootstrap:
    initdb:
      database: code-place
      owner: code-place
      secret:
        name: pg-credentials
