apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: regcred
  namespace: code-place-prod
spec:
  encryptedData:
    .dockerconfigjson: AgDVovltOgTgDY8XSjXYqg/grx1+aAvqisGroF/f+TTrXc+x2eDAtYxdk0tPV1gnuMwR0C6QXcRHAKXF+hdEhb8N/rUeXZybJAXv7XAbr5g1nuOmdgLco4/YTUFqPelbuIvtZ606ZQ123G7vON5SvJE39pCkMDi1MTszkd9+3rbShuu1jcYYmzFGbeToAysHdzUDg3IQVYWc7BtQLhpx/Z3LivOUGoywL1LCbM8bDA9EXVLy/ofw2KLfIt74EgtbrMN97/+m2+jPHyj8eREEHWPEzuM5NZC/lfEjtuv9uwBEC8w1VApQzQuz7qT7AGio2/HapZHj4aiB4r2FYje0OCH4dCd75PQVPBXAEY6MAzIAUSlREsrSh9jGvmCxecWh9cSgWGKF446yCbM47MFhyX+BZcau+02gaPzSjkqXaK7SFPVreW7AKT0BdbRECu9qNCDogtaxQLFxDdKLP/tWNZrbFmzCyGqC6zbchSPFADYUnM/ygYxC4UdO+cE1ccm0VIT0NeSu5oEAJpQzfhq5WWfGDPoqOZz39c3UpUbR0K+f+JGqw1XXa/g0+APvgMCylfSQWmlx3JvVT/iMG5IvniMPHiMNMhWNk/UrLXnmJ75wBIywsTCa+RlrC57E6lnx1rR00IyEQoooluvLncvddUdpzgcegkt66qWvyJyckLsvd/AsAcHUnpsGOfG3fgEvKMvWrPqBV5NFCjQVONFBtI/DmDdb9+jODd2tuNZCk+O8gMB88Aiqkzi/UKpV5D3V5mUEUMEUSFq1vpXMRTv2I/rJagze+TGY9eQ2yJLifZA0Vvg/feV90c+oCrbYt5Lca8MnbdbZJOuSvRFPDxbIsoZj5D9H0Z1g+A==
  template:
    metadata:
      name: regcred
      namespace: code-place-prod
    type: kubernetes.io/dockerconfigjson
