# kubernetes/base/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # Persistent Volume Claims
  - ./backend/pvc.yaml

  # Database and Cache
  - ./postgres/postgres.yaml
  - ./redis/redis.yaml

  # Application Services
  - ./backend/service.yaml
  - ./frontend/service.yaml

  # Application Deployments
  - ./backend/deployment.yaml
  - ./frontend/deployment.yaml

  # Ingress Resources
  - ./frontend/ingress.yaml

commonLabels:
  app.kubernetes.io/managed-by: kustomize
