# NOTE: Longhorn + RWX 볼륨은 NFS 기반으로 다중 파드에서 읽기/쓰기가 가능한 대신 성능이 다소 떨어질 수 있습니다.
# 따라서 I/O 성능이 중요한 경우에는 별도의 스토리지 클래스를 사용하여 RWX 대신 RWO 볼륨을 사용하는 것을 권장합니다.
# 또한, 각 서비스의 로그는 PVC에 저장하지 않고 `emptyDir`에 저장하고, 추후 로그 수집기를 통해 중앙 집중식으로 관리해야 합니다. (Junwoo)
---
# 테스트케이스 (Backend, JudgeServer에서 사용)
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-testcase
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 10Gi

---
# 퍼블릭 정적 파일 (Backend, Frontend에서 사용)
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-public
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 5Gi

---
# 설정 파일 (Backend에서 사용)
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-config
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
