apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: regcred
  namespace: code-place-stage
spec:
  encryptedData:
    .dockerconfigjson: AgBvQudUO/gEAyqAyUuloj+ftfeuAR+h3/miSLUTXRdjnSHkDFHyWukM5YSjbBBs8Iadsx4TLDxPvZbo//x5u0iVlAJBs4IznrS8eoOUU0a+ySniLVOJP8Ks6mp38/Yt1eMO8+R24+cDNtNPyRTqQVuf39egKYA8ei4Yy/1FFcyWO9W1XU0WOuU/gIKKc1mdks4e8nX17oukl7GLIyBWEO6WPa+que3z0CjQDcmw+Q/4jOL8FxlvYXQJLF9hp2busM8R/eXFmQ7fXdc8piAlwkMWAI48YZ5v2Y8mWvuVMTWcPRKPGZgJzIRGHedQoLLhHg5cw/f5rHrxZkKZMnTqiCiGOksFjR4gYV6ueBUWxofbL8SNAX2SFqSPyo8nyZNZvNag9bRSCWDxkAKHJW1jfXfwwV8mZGz8u3PDXvTT20XrvEuuNMLLw8XP0EQMQHgkn6tVIknB7FML4+in8A+mHbill/VIzmhULTMhsb2w+XkEybfcoIjACrJoPuz2UElOnoQI/x5jP4CNTY4nwePnp7noWzyW4HaC9Kcw0qqK9DsmO7QtlOZZ0wPd8EEDGf5bzam55E9qjiAG9iP5AiUVuVM/uTgzVc4itWUpfgCQvPl1uS+2K8YjYUeSiaNNEuCqi0LbotN31YfXmTwadQorGPxHxcg/V6TkW1xFevsmFBwE4rY5XhtLr9G0RIWU7JF+npVdw+09RG43uqq5GhEaiQqKA4WG69CPZUeVUR3GQos9gocPkYmGLuIr8jBozEns1hJu/w8VuCvbkir5l+g5dkR/YFskOQQsP8q8rUF0ZjzHpS0FW2oh6LzzT4BhUJdnKhDdcSAtOpYGeo5orUW2RzSpVFHwqe3kABKi
  template:
    metadata:
      name: regcred
      namespace: code-place-stage
    type: kubernetes.io/dockerconfigjson
