# kubernetes/base/judge/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: judge-server
  labels:
    app: judge-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: judge-server
  template:
    metadata:
      labels:
        app: judge-server
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: judge-server
          image: registry.code-place-dev.site/code-place-dev/judge-server:1.0.3
          imagePullPolicy: IfNotPresent
          securityContext:
            capabilities:
              drop:
                - SETPCAP
                - MKNOD
                - NET_BIND_SERVICE
                - SYS_CHROOT
                - SETFCAP
                - FSETID
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "500Mi"
              cpu: "1000m"
            limits:
              memory: "1Gi"
              cpu: "2000m" # TODO: 추후 채점 서버를 단일 프로세스로 변경하고, cgroup 종속성을 제거한 뒤 CPU Limit 제거
          livenessProbe:
            exec:
              # 채점 서버 Heart Beat API를 호출하여 상태 확인
              command:
                - /app/.venv/bin/python3
                - /app/service.py
            initialDelaySeconds: 30
            periodSeconds: 5
          env:
            - name: SERVICE_URL
              value: "http://judge-server:8080"
            - name: BACKEND_URL
              value: "http://backend:8080/api/judge_server_heartbeat"
            - name: TOKEN
              valueFrom:
                secretKeyRef:
                  name: common-credentials
                  key: JUDGE_SERVER_TOKEN
          volumeMounts:
            - name: vol-tmp
              mountPath: /tmp
            - name: vol-log
              mountPath: /log
            - name: vol-run
              mountPath: /judger
            - name: vol-testcase
              mountPath: /test_case
              readOnly: true
      volumes:
        - name: vol-tmp
          emptyDir: {}
        - name: vol-log
          emptyDir: {}
        - name: vol-run
          emptyDir: {}
        - name: vol-testcase
          persistentVolumeClaim:
            claimName: pvc-testcase
