# kubernetes/base/judge/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: judge-server
  labels:
    app: judge-server
spec:
  selector:
    app: judge-server
  ports:
    - name: api
      port: 8080
      targetPort: 8080
      protocol: TCP
